# Generated by Django 4.2.6 on 2023-11-09 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='katagori',
            new_name='kategori',
        ),
        migrations.AddField(
            model_name='produk',
            name='kategori',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='members.kategori'),
            preserve_default=False,
        ),
    ]
